version: 2
job:
  build:
    docker:
    - image: circleci/node:10.15.3
    working_directory: ~/repo
    orbs:
      cypress: cypress-io/cypress@1
      percy: percy/agent@0.1.2
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run: npm install 
    - run: npm ci
    - run: test:e2e
    - run: npm run build
    - save_cache:
        paths:
        - node_modules
        - dist
        - package.json
        key: v1-dependencies-{{ checksum "package.json" }}
job:
  node_8:
    docker:
      - image: circleci/node:8-browsers
    environment:
      PERCY_ENABLE: 0
      
  node_10_with_percy:
    # We've opted this node version to be the one that runs and reports Percy's status
    docker:
      - image: circleci/node:10-browsers
        
workflows:
  version: 2
  workflow:
    jobs:
    - node_8
    - node_10_with_percy
    - build