version: 2.1

orbs:
 percy: percy/agent@0.1.2

jobs:
 run_tests:
   parallelism: 3
   steps:
     - attach_workspace:
         at: ~/repo
     - run: echo "your tests run here"
jobs:
  build:
    docker:
    - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run: npm install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - run: npx vue-cli-service build
workflows:
 test:
   jobs:
    - build
    - run_tests
    - percy/finalize_all:
         requires:
           - run_tests
    