version: 2
orbs:
 percy: percy/agent@0.1.2

jobs:
  build:
    docker:
    - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run: npm install
    - save_cache:
        paths:
        - node_modules
        key: v1-dependencies-{{ checksum "package.json" }}
    - run: npm run build
    - run: npx percy snapshot _site
workflows:
  version: 2
  workflow:
    jobs:
    - build