version: 2
jobs:
  build:
    docker:
    - image: circleci/node:10.15.3
    working_directory: ~/repo
    orbs:
      cypress: cypress-io/cypress@1
      percy: percy/agent@0.1.2
    steps:
    - checkout
    - restore_cache:
        keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies-
    - run: npm install
    - run: docker run -it -v $PWD:/e2e -w /e2e cypress/included:3.2.0
    - run: npx percy exec -- cypress run --record
    - run: npm run build
    - save_cache:
        paths:
        - node_modules
        - dist
        - package.json
        key: v1-dependencies-{{ checksum "package.json" }}
    
workflows:
  version: 2
  workflow:
    jobs:
    - build