# https://circleci.com/orbs/registry/licensing for details.
version: "2.1"
description: Workflow for running Percy builds in parallel. Your token will be read from $PERCY_TOKEN by default, but this
  can be overridden using the `percy_token` parameter.

examples:
  finalize_all_percy_builds:
    description: Finalize all Percy builds
    usage:
      version: 2.1

      orbs:
        percy: percy/agent@1.0.0

      workflows:
        percy_finalize_all:
          jobs:
            - percy/finalize_all

executors:
  default:
    docker:
      - image: cypress-percy-test
working_directory: ~/repo
commands:
  finalize_all:
    description: Finalize all Percy builds
    parameters:
      percy_token:
        description: PERCY_TOKEN for your project. It is found on your project settings.
        type: string
        default: $PERCY_TOKEN
    steps:
      - run: 
          name: install dependencies 
          command: |
            PERCY_TOKEN=<< parameters.percy_token >> percy finalize --all
            npm install
       - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }
jobs:
  finalize_all:
    executor: default
    steps:
      - run:
          name: run tests
          command: |
            npm run build
            percy snapshot _site